Repository uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager, pull requests merged in 2024-03, with the labels that each got.

#132 Finished Calendar System Framework
  src/app/Calendar.js
  src/app/page.js
Labels: Feature

#135 Changed pie chart to be a dynamic donut chart
  src/app/ExpenseChart.js
  src/app/page.js
Labels: enhancement

#145 data visualization line chart enhancement
  src/app/lineChart.js
Labels: enhancement

#151 Calendar systems time based income and expenses
  src/app/AddExpensesModal.js
  src/app/AddIncomesModal.js
  src/app/ViewExpenseModal.js
Labels: enhancement, Feature

#166 Data Visualization: Pie Chart Custom Aesthetic
  src/app/ExpenseChart.js
  src/app/globals.css
Labels: enhancement

#175 Calendar systems: interactive tiles to add incoming events and expected expenses
  src/app/Calendar.css
  src/app/Calendar.js
  src/app/globals.css
Labels: enhancement

#182 Calendar Systems: Event History for the day
  src/app/Calendar.css
  src/app/Calendar.js
Labels: enhancement

#192 Improved if-else logic in page.js
  src/app/page.js
Labels: enhancement, Page Structure

#194 Enhanced 'My Balance' Section Responsiveness
  src/app/globals.css
  src/app/page.js
Labels: enhancement, Page Structure

#203 Enhanced 'Income' And 'Expenses' Buttons
  src/app/globals.css
  src/app/page.js
Labels: enhancement, Page Structure

#205 Centralization of Page UI
  package-lock.json
  package.json
  src/app/globals.css
  src/app/page.js
Labels: enhancement, Page Structure

#243 Better Legibility on calendar timer, month, year and days
  src/app/globals.css
Labels: enhancement, Page Structure

#208 150 calendar systems interactive months tiles
  src/app/Calendar.css
  src/app/Calendar.js
Labels: enhancement

#252 Changed the background of the LogIn page to a darker theme to match the wireframe theme
  src/app/Page-Functionality/Calendar.css
  src/app/Page-Functionality/Calendar.js
  src/app/Pages/LoginPage.js
  src/app/globals.css
Labels: enhancement, Page Structure

#250 Table Analysis Modal
  src/app/Modals/tableAnalysisModal.js
  src/app/Page-Functionality/Filters/moneyFilters.js
  src/app/page.js
Labels: Feature

#195 Sign up page & Login page with all features
  package-lock.json
  src/app/Page-Functionality/Login/ForgotPassword.js
  src/app/Pages/LoginPage.js
  src/app/Pages/SignUpPage.js
  src/app/page.js
Labels: Feature, Page Structure
