Repository uprm-inso4101-2023-2024-s2/semester-project-personalfinancemanager, pull requests merged in 2024-04, with the labels that each got.

#246 Change color in expense category
  src/app/Finance-Context/finance-context.js
  src/app/Modals/ViewExpenseModal.js
Labels: enhancement, Page Structure

#284 Changed color on the month selection dropdown to match the budget button
  src/app/Page-Functionality/Calendar.css
Labels: Page Structure

#277 Time-Based Bar Chart
  src/app/Charts/barChart.js
  src/app/Page-Functionality/Filters/moneyFilters.js
  src/app/globals.css
Labels: enhancement

#285 AddIncomeModal label/fields colors modified
  src/app/Modals/AddIncomesModal.js
  src/app/globals.css
Labels: Page Structure

#287 Navigation Menu close button placement
  package-lock.json
  package.json
  src/app/Page-Functionality/AddMenu.js
Labels: enhancement, Page Structure

#286 Finished Calendar System: Responsive Pie Chart
  src/app/Charts/ExpenseChart.js
  src/app/globals.css
Labels: enhancement

#291 ExpensesModal Label Colors Modified
  src/app/Modals/AddExpensesModal.js
  src/app/globals.css
Labels: Page Structure

#305 258 improve budget button and modals
  src/app/Modals/AddExpensesModal.js
  src/app/Modals/AddIncomesModal.js
  src/app/Modals/modal.js
  src/app/Page-Functionality/Calendar.css
  src/app/Page-Functionality/Calendar.js
Labels: bug, enhancement

#306 Calendar System: Visual Overhaul
  src/app/Page-Functionality/Calendar.css
  src/app/Page-Functionality/Calendar.js
Labels: bug, enhancement

#307 177 calendar system interactive tile improvement
  src/app/Charts/barChart.js
  src/app/Charts/charts.css
  src/app/Charts/divergingBarChart.js
  src/app/Finance-Context/finance-context.js
  src/app/Modals/tableAnalysisModal.js
  src/app/Page-Functionality/Calendar.js
Labels: bug, enhancement

#328 Added colored background to active button in side NavBar
  src/app/Page-Functionality/AddMenu.js
Labels: enhancement, Page Structure

#331 Implement enclosing box for enhanced visual structure of balance and buttons
  src/app/globals.css
  src/app/page.js
Labels: Page Structure

#332 fixed Calendar layer overlapping nav bar
  src/app/Page-Functionality/AddMenu.js
Labels: Page Structure

#334 Fixed balance amount going over balance box
  src/app/globals.css
Labels: Page Structure

#336 Improved Style & Responsiveness of 'Sign Up' page and formated code.
  src/app/Pages/SignUpPage.js
Labels: Page Structure

#326 309 progressbar visual overhaul dbc visual fix
  package-lock.json
  src/app/Charts/divergingBarChart.js
  src/app/Page-Functionality/Calendar.css
  src/app/Page-Functionality/Calendar.js
Labels: bug, enhancement

#339 Show/Hide Expenses Button
  src/app/page.js
Labels: enhancement, Page Structure

#312 280 change color on closing buttons
  src/app/Modals/modal.js
Labels: enhancement, Page Structure

#337 Toggle button for viewing Expenses and Encomes in Bar Chart
  src/app/Charts/barChart.js
  src/app/Charts/charts.css
  src/app/page.js
Labels: enhancement

#340 301 create separate page for graphs section
  src/app/Page-Functionality/AddMenu.js
  src/app/Page-Functionality/Navigations.js
  src/app/Page-Functionality/graphcontext.js
  src/app/Pages/GraphsPage.js
  src/app/globals.css
  src/app/layout.js
  src/app/page.js
Labels: enhancement, Page Structure

#367 311 create separate page for calendar section
  src/app/Page-Functionality/AddMenu.js
  src/app/Page-Functionality/Navigations.js
  src/app/Page-Functionality/calendarContext.js
  src/app/Pages/CalendarPage.js
  src/app/layout.js
  src/app/page.js
Labels: Feature, Page Structure
